// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bingbong.Models;

namespace bingbong.Migrations
{
    [DbContext(typeof(GamerContext))]
    partial class GamerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("bingbong.Models.Gamers", b =>
                {
                    b.Property<int>("GamersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("gamerTag")
                        .HasColumnType("TEXT");

                    b.HasKey("GamersId");

                    b.ToTable("Gamer");
                });
#pragma warning restore 612, 618
        }
    }
}
